services:
    node:
        #        build: .
        image: rorem/zentrity
        container_name: ${MODE}
        ports:
            - ${PORT}:${PORT}
        expose:
            - ${PORT}
        environment:
            - SERVER_URL
            - DB_URL
            - DOMAIN
            - PORT
            - MODE=production
            - ENCRYPT_TOKEN
